services:
    api.exception_subscriber:
        class: AppBundle\Subscriber\ExceptionSubscriber
        tags:
           - { name: kernel.event_subscriber }

    api.response.builder:
        class: AppBundle\Api\Response\ResponseBuilder
        arguments: ['@serializer']